# Generated by Django 2.0.2 on 2018-03-12 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gibdd_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='category_dr_license_data',
            field=models.ManyToManyField(to='gibdd_app.Category', verbose_name='Данные о доступных категорях'),
        ),
        migrations.AlterField(
            model_name='licensedisqualification',
            name='disqualif_alcohol_amount',
            field=models.FloatField(blank=True, null=True, verbose_name='Промилле алкоголя в крови'),
        ),
        migrations.AlterField(
            model_name='licensedisqualification',
            name='disqualif_cause',
            field=models.CharField(blank=True, default='Вождение автомобиля под воздействием алкоголя', max_length=200, null=True, verbose_name='Причина лишения'),
        ),
        migrations.AlterField(
            model_name='licensedisqualification',
            name='disqualif_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='licensedisqualification',
            name='disqualif_date_end',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания лишение прав'),
        ),
        migrations.AlterField(
            model_name='licensedisqualification',
            name='disqualif_date_from',
            field=models.DateField(blank=True, null=True, verbose_name='Дата лишения прав'),
        ),
        migrations.AlterField(
            model_name='licensedisqualification',
            name='disqualif_status',
            field=models.CharField(choices=[('Действующие', 'Действующие'), ('Лишение', 'Лишение'), ('Просрочены', 'Просрочены')], max_length=20, verbose_name='Статус прав'),
        ),
    ]
