# Generated by Django 2.0.2 on 2018-04-10 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gibdd_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licensedisqualification',
            name='disqualif_cause',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Причина лишения'),
        ),
        migrations.AlterField(
            model_name='medicalcertificate',
            name='medical_number',
            field=models.CharField(max_length=10, verbose_name='Номер справки'),
        ),
    ]
