# Generated by Django 2.0.2 on 2018-03-27 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gibdd_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fine',
            name='fine_decree_data',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gibdd_app.Decree', verbose_name='Данные о постановлении'),
        ),
    ]
