# Generated by Django 2.0.2 on 2018-03-08 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gibdd_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='license',
            name='category_dr_license_data',
        ),
        migrations.AddField(
            model_name='license',
            name='category_dr_license_data',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gibdd_app.Category', verbose_name='Данные о доступных категорях'),
        ),
        migrations.AlterField(
            model_name='license',
            name='driver_data',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gibdd_app.Driver', verbose_name='Данные о водителе'),
        ),
        migrations.AlterField(
            model_name='license',
            name='status_dr_license',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gibdd_app.LicenseDisqualification', verbose_name='Статус прав'),
        ),
    ]
