# Generated by Django 2.0.2 on 2018-04-10 21:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gibdd_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='date_end_dr_license',
            field=models.DateField(blank=True, default=datetime.date(2028, 4, 11), editable=False, null=True, verbose_name='Дата окончания действия ВУ'),
        ),
    ]
