# Generated by Django 2.0.2 on 2018-03-13 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gibdd_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lisense_category',
            name='licen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gibdd_app.License', unique=True, verbose_name='Все ВУ'),
        ),
    ]
