# Generated by Django 2.0.2 on 2018-03-12 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gibdd_app', '0002_auto_20180312_2154'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lisense_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gibdd_app.Category', verbose_name='Все категории')),
            ],
        ),
        migrations.RemoveField(
            model_name='license',
            name='category_dr_license_data',
        ),
        migrations.AddField(
            model_name='lisense_category',
            name='licen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gibdd_app.License', verbose_name='Все ВУ'),
        ),
    ]
