# Generated by Django 2.0.2 on 2018-04-10 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gibdd_app', '0002_auto_20180410_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='driver_birth',
            field=models.DateField(verbose_name='Дата рождения водителя'),
        ),
    ]
