# Generated by Django 2.0.2 on 2018-04-11 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gibdd_app', '0002_auto_20180411_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspector',
            name='inspector_number_token',
            field=models.CharField(max_length=9, unique=True, verbose_name='Номер жетона'),
        ),
    ]
