# Generated by Django 2.0.2 on 2018-03-09 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gibdd_app', '0002_auto_20180308_2223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='contents_category',
        ),
    ]
