# Generated by Django 2.0.2 on 2018-04-18 11:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gibdd_app', '0002_auto_20180417_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='date_end_dr_license',
            field=models.DateField(blank=True, default=datetime.date(2028, 4, 18), editable=False, null=True, verbose_name='Дата окончания действия ВУ'),
        ),
        migrations.AlterUniqueTogether(
            name='accidentreport',
            unique_together={('accident_date', 'accident_causer_person')},
        ),
    ]
