# Generated by Django 2.0.2 on 2018-03-27 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gibdd_app', '0002_auto_20180327_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fine',
            name='date_of_payment_fine',
            field=models.DateTimeField(verbose_name='Дата оплаты штрафа'),
        ),
        migrations.AlterField(
            model_name='fine',
            name='fine_discount',
            field=models.FloatField(verbose_name='Скидка'),
        ),
    ]
