# Generated by Django 2.0.2 on 2018-03-13 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gibdd_app', '0003_auto_20180313_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lisense_category',
            name='categ',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gibdd_app.Category', verbose_name='Все категории'),
        ),
    ]
