# Generated by Django 2.0.2 on 2018-04-13 19:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gibdd_app', '0003_auto_20180411_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autoschool',
            name='school_category_dr_license',
            field=models.CharField(max_length=40, verbose_name='Обучение на категорию'),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='insurance_number',
            field=models.CharField(help_text='ЕЕЕ№1234567890', max_length=14, unique=True, verbose_name='Номер полиса'),
        ),
        migrations.AlterField(
            model_name='license',
            name='date_end_dr_license',
            field=models.DateField(blank=True, default=datetime.date(2028, 4, 13), editable=False, null=True, verbose_name='Дата окончания действия ВУ'),
        ),
    ]
