# Generated by Django 2.0.2 on 2018-03-09 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gibdd_app', '0003_remove_category_contents_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalcertificate',
            name='med_photo_1',
            field=models.ImageField(blank=True, upload_to='med_photo/', verbose_name='Скан медицинской справки, лицевая сторона'),
        ),
        migrations.AlterField(
            model_name='medicalcertificate',
            name='med_photo_2',
            field=models.ImageField(blank=True, upload_to='med_photo/', verbose_name='Скан медицинской справки, обратная сторона'),
        ),
    ]
