# Generated by Django 2.0.2 on 2018-03-27 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gibdd_app', '0003_auto_20180327_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decree',
            name='decree_total_speed',
            field=models.IntegerField(blank=True, null=True, verbose_name='Скорость движения в момент нарушения'),
        ),
        migrations.AlterField(
            model_name='decree',
            name='decree_violation_text',
            field=models.TextField(blank=True, null=True, verbose_name='Полное описание нарушения'),
        ),
        migrations.AlterField(
            model_name='license',
            name='status_dr_license',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gibdd_app.LicenseDisqualification', verbose_name='Подробности лишения прав'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='owner_comment',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Особые отметки'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='owner_district',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Район'),
        ),
    ]
