# Generated by Django 2.0.2 on 2018-04-14 05:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gibdd_app', '0004_auto_20180413_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='date_end_dr_license',
            field=models.DateField(blank=True, default=datetime.date(2028, 4, 14), editable=False, null=True, verbose_name='Дата окончания действия ВУ'),
        ),
    ]
