# Generated by Django 2.0.2 on 2018-03-29 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gibdd_app', '0004_auto_20180327_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accidentreport',
            name='accident_photo_1',
            field=models.ImageField(blank=True, default='accident_photo/default.jpg', null=True, upload_to='accident_photo/', verbose_name='Первое фото аварии'),
        ),
        migrations.AlterField(
            model_name='accidentreport',
            name='accident_photo_2',
            field=models.ImageField(blank=True, default='accident_photo/default.jpg', null=True, upload_to='accident_photo/', verbose_name='Второе фото аварии'),
        ),
        migrations.AlterField(
            model_name='fine',
            name='date_of_payment_fine',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата оплаты штрафа'),
        ),
    ]
