# Generated by Django 2.0.2 on 2018-04-19 14:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gibdd_app', '0004_auto_20180418_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gibdd_app.Owner', verbose_name='Собственник автомобиля'),
        ),
        migrations.AlterField(
            model_name='license',
            name='date_end_dr_license',
            field=models.DateField(blank=True, default=datetime.date(2028, 4, 19), editable=False, null=True, verbose_name='Дата окончания действия ВУ'),
        ),
    ]
