# Generated by Django 2.0.2 on 2018-03-29 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gibdd_app', '0005_auto_20180329_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accidentreport',
            name='number_accident',
            field=models.CharField(max_length=40, verbose_name='Номер протокола аварии'),
        ),
    ]
