# Generated by Django 2.0.2 on 2018-03-13 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gibdd_app', '0005_auto_20180313_1454'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lisense_category',
            unique_together=set(),
        ),
    ]
