# Generated by Django 2.0.2 on 2018-03-29 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gibdd_app', '0006_auto_20180329_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosticcard',
            name='diagnostic_company',
            field=models.CharField(max_length=200, verbose_name='Пункт технического осмотра'),
        ),
    ]
