# Generated by Django 2.0.2 on 2018-03-13 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gibdd_app', '0006_auto_20180313_1518'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lisense_category',
            unique_together={('licen', 'categ')},
        ),
    ]
