# Generated by Django 2.0.2 on 2018-03-15 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gibdd_app', '0007_auto_20180313_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='medical_certificate_data',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gibdd_app.MedicalCertificate', verbose_name='Данные о мед.справках'),
        ),
    ]
