# Generated by Django 2.0.2 on 2018-04-01 14:28

import datetime
from django.db import migrations, models
import gibdd_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('gibdd_app', '0008_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='driver_birth',
            field=models.DateTimeField(verbose_name='Дата рождения водителя'),
        ),
        migrations.AlterField(
            model_name='license',
            name='date_end_dr_license',
            field=models.DateField(blank=True, default=gibdd_app.models.get_deadline, editable=False, null=True, verbose_name='Дата окончания действия ВУ'),
        ),
        migrations.AlterField(
            model_name='license',
            name='date_issue_dr_license',
            field=models.DateField(default=datetime.datetime.now, editable=False, verbose_name='Дата выдачи ВУ'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='group',
            field=models.CharField(choices=[('Администратор', 'Администратор'), ('Инспектор', 'Инспектор'), ('Регистрирующий оператор', 'Регистрирующий оператор'), ('Основной оператор', 'Основной оператор'), ('Справочная', 'Справочная'), ('Страховщик', 'Страховщик')], max_length=25),
        ),
    ]
