# Generated by Django 2.0.2 on 2018-03-24 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gibdd_app', '0008_auto_20180315_1215'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lisense_Accident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gibdd_app.AccidentReport', verbose_name='Список ДТП')),
                ('licen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gibdd_app.License', verbose_name='Все ВУ')),
            ],
        ),
        migrations.AlterField(
            model_name='autoschool',
            name='school_category_dr_license',
            field=models.CharField(max_length=20, verbose_name='Обучение на категорию'),
        ),
        migrations.AlterUniqueTogether(
            name='lisense_accident',
            unique_together={('licen', 'accid')},
        ),
    ]
