# Generated by Django 2.0.2 on 2018-04-03 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gibdd_app', '0009_auto_20180401_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accidentreport',
            name='accident_severity',
            field=models.CharField(blank=True, choices=[('легкая', 'легкая'), ('средней тяжести', 'средней тяжести'), ('тяжкий вред', 'тяжкий вред'), ('без вреда здоровью', 'без вреда здоровью'), ('не указано', 'не указано')], default='не указано', max_length=50, null=True, verbose_name='Тяжесть аварии'),
        ),
    ]
