# Generated by Django 2.0.2 on 2018-03-24 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gibdd_app', '0010_remove_accidentreport_accident_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accidentreport',
            name='accident_cause',
            field=models.CharField(max_length=250, verbose_name='Причина аварии'),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_stealing',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gibdd_app.Stealing', verbose_name='Детали угона'),
        ),
        migrations.AlterField(
            model_name='fine',
            name='fine_car_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gibdd_app.Car', verbose_name='Штраф для автомобиля'),
        ),
    ]
