# Generated by Django 2.0.2 on 2018-04-05 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gibdd_app', '0010_auto_20180403_1058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='member',
        ),
        migrations.AlterField(
            model_name='camera',
            name='camera_name',
            field=models.CharField(choices=[('Радар Стрелка СТ/М', 'Радар Стрелка СТ/М'), ('Система Автодория', 'Система Автодория'), ('Фоторадарные комплексы КРИС С', 'Фоторадарные комплексы КРИС С'), ('Фоторадарные комплексы КРИС П', 'Фоторадарные комплексы КРИС П'), ('Радар Кречет-С', 'Радар Кречет-С'), ('Радар Перекресток', 'Радар Перекресток'), ('Комплекс фотовидеофиксации "Сова"', 'Комплекс фотовидеофиксации "Сова"'), ('Комплекс фотовидеофиксации "Одиссей"', 'Комплекс фотовидеофиксации "Одиссей"'), ('Паркон', 'Паркон')], max_length=100, verbose_name='Название камеры'),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_status',
            field=models.CharField(choices=[('Стоит на учете', 'Стоит на учете'), ('Снят на учете', 'Снят на учете'), ('Числится в угоне', 'Числится в угоне')], default='Стоит на учете', max_length=20, verbose_name='Статус автомобиля'),
        ),
        migrations.AlterField(
            model_name='registrationcertificate',
            name='registr_certificate_category',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('прицеп', 'прицеп')], default='B', max_length=5, verbose_name='Категория ТС'),
        ),
        migrations.AlterField(
            model_name='registrationcertificate',
            name='registr_certificate_type_car',
            field=models.CharField(choices=[('легковой', 'легковой'), ('грузовой', 'грузовой'), ('автобус', 'автобус'), ('мотоцикл', 'мотоцикл'), ('прицеп', 'прицеп'), ('полуприцеп', 'полуприцеп'), ('универсал легковой', 'универсал легковой'), ('хэтчбек(комби) легковой', 'хэтчбек(комби) легковой'), ('легковой прочие', 'легковой прочие'), ('бортовой с тентом грузовой', 'бортовой с тентом грузовой'), ('грузовой фургон', 'грузовой фургон'), ('легковой минивэн', 'легковой минивэн'), ('грузовой бортовой', 'грузовой бортовой'), ('легковой седан', 'легковой седан'), ('легковой купе', 'легковой купе')], default='легковой', max_length=60, verbose_name='Тип ТС'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
