# Generated by Django 2.0.2 on 2018-04-06 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gibdd_app', '0011_auto_20180405_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autoschool',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gibdd_app.Driver', unique=True, verbose_name='Ученик автошколы'),
        ),
    ]
