# Generated by Django 2.0.2 on 2018-03-25 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gibdd_app', '0011_auto_20180324_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalcertificate',
            name='validity',
            field=models.CharField(blank=True, choices=[('MONTH6', '6 месяцев'), ('YEAR1', '1 год'), ('YEAR2', '2 года'), ('other', 'другое')], default='1 год', max_length=11, null=True, verbose_name='Срок действия справки'),
        ),
    ]
