# Generated by Django 2.0.2 on 2018-04-06 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gibdd_app', '0012_auto_20180406_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosticcard',
            name='diagnostic_number',
            field=models.CharField(max_length=15, unique=True, verbose_name='Регистрационный номер'),
        ),
    ]
