# Generated by Django 2.0.2 on 2018-04-06 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gibdd_app', '0013_auto_20180406_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosticcard',
            name='diagnostic_car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gibdd_app.Car', unique=True, verbose_name='Автомобиль для диагностики'),
        ),
    ]
