# Generated by Django 2.0.2 on 2018-04-06 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gibdd_app', '0014_auto_20180406_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accidentreport',
            name='accident_inspector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gibdd_app.Inspector', verbose_name='Инспектор, оформивший ДТП'),
        ),
        migrations.AlterField(
            model_name='autoschool',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gibdd_app.Driver', verbose_name='Ученик автошколы'),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_stealing',
            field=models.OneToOneField(blank=True, default=' Не числится в угоне', null=True, on_delete=django.db.models.deletion.CASCADE, to='gibdd_app.Stealing', verbose_name='Детали угона'),
        ),
        migrations.AlterField(
            model_name='diagnosticcard',
            name='diagnostic_car',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gibdd_app.Car', verbose_name='Автомобиль для диагностики'),
        ),
    ]
