# Generated by Django 2.0.2 on 2018-04-08 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gibdd_app', '0015_auto_20180406_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_stealing',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gibdd_app.Stealing', verbose_name='Детали угона'),
        ),
    ]
