# Generated by Django 2.0.2 on 2018-04-08 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gibdd_app', '0016_auto_20180408_2149'),
    ]

    operations = [
        migrations.CreateModel(
            name='Europrotocol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('europrotocol_date', models.DateField(verbose_name='День составления протокола')),
                ('europrotocol_scan_1', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Скан лицевой стороны европротокола')),
                ('europrotocol_scan_2', models.ImageField(blank=True, null=True, upload_to='', verbose_name=' Скан оборотной стороны европротокола')),
                ('europrotocol_car_1', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='europrotocol_car_1', to='gibdd_app.Car')),
                ('europrotocol_car_2', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='europrotocol_car_2', to='gibdd_app.Car')),
                ('europrotocol_driver_1', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='europrotocol_driver_1', to='gibdd_app.Driver')),
                ('europrotocol_driver_2', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='europrotocol_driver_2', to='gibdd_app.Driver')),
                ('europrotocol_insurance_1', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='europrotocol_insurance_1', to='gibdd_app.Insurance')),
                ('europrotocol_insurance_2', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='europrotocol_insurance_2s', to='gibdd_app.Insurance')),
                ('europrotocol_license_1', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='europrotocol_license_1', to='gibdd_app.License')),
                ('europrotocol_license_2', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='europrotocol_license_2', to='gibdd_app.License')),
            ],
        ),
        migrations.AlterField(
            model_name='stealing',
            name='stealing_status',
            field=models.CharField(blank=True, choices=[('Не числится в угоне', 'Не числится в угоне'), ('Числится в угоне', 'Числится в угоне')], max_length=25, null=True, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='accidentreport',
            name='accident_europrotocol',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gibdd_app.Europrotocol', verbose_name='ДТП по европротоколу'),
        ),
    ]
